version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: guacamole_db
    networks:
      - guacanet
  guacd:
    image: glyptodon/guacd
    networks:
      - guacanet
  guacamole:
    image: glyptodon/guacamole
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
    networks:
      - guacanet
    depends_on:
      - postgres
      - guacd

volumes:
  data:
    driver: local

networks:
  guacanet:
    external: true
